/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_leolin_samples_android_ndk_NdkService */

#ifndef _Included_me_leolin_samples_android_ndk_NdkService
#define _Included_me_leolin_samples_android_ndk_NdkService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_leolin_samples_android_ndk_NdkService
 * Method:    provideInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_leolin_samples_android_ndk_NdkService_provideInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
